In [ ]:
https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [6]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.97473696, 0.55904036, 0.5838587 , 0.61701874],
       [0.18680083, 0.19850595, 0.35241328, 0.48301734],
       [0.46512125, 0.0610068 , 0.78142941, 0.31916999]])

In [9]:
from numpy.random import normal 
normal_value=normal(size=(3,4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [12]:
#ndarray,陣列運算
normal_value * 5

array([[-7.44350085, -8.07263605, -5.65085872, -1.19348697],
       [-3.17443319, -9.52320637, -2.362156  ,  2.02787861],
       [ 4.78009282, -3.49684081,  1.21451412,  3.14513903]])

In [11]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([-4.47209652, -2.60638339,  1.12858103])

In [13]:
import numpy as np
x = np.random.random()
print(x)

0.4907894760852717
