In [ ]:
https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [6]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.97473696, 0.55904036, 0.5838587 , 0.61701874],
       [0.18680083, 0.19850595, 0.35241328, 0.48301734],
       [0.46512125, 0.0610068 , 0.78142941, 0.31916999]])

In [9]:
from numpy.random import normal 
normal_value=normal(size=(3,4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [10]:
#ndarray,陣列運算
normal_value * 10

array([[-14.88700171, -16.14527211, -11.30171744,  -2.38697394],
       [ -6.34886638, -19.04641273,  -4.724312  ,   4.05575721],
       [  9.56018564,  -6.99368162,   2.42902825,   6.29027805]])

In [11]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([-4.47209652, -2.60638339,  1.12858103])